name: dragonboard-kernel
summary: Snapdragon kernel for snappy
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel
architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

parts:
    kernel:
        after:
            - skales
            - firmware
            - firmware-ath10k
            - firmware-dragonboard410c
            - firmware-dragonboard820c
            - firmware-dragonboard845c
            - firmware-qcom-media
        plugin: kernel
        source: .
        source-type: git
        source-depth: 1
        kconfigflavour: snapdragon
        kernel-with-firmware: false
        kernel-image-target: Image.gz
        kconfigs:
            - CONFIG_LOCALVERSION_AUTO=n
            - CONFIG_DEBUG_INFO=n
            - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
            - CONFIG_BLK_DEV_BSG=y
            - CONFIG_CC_STACKPROTECTOR=y
            - CONFIG_CC_STACKPROTECTOR_STRONG=y
            - CONFIG_DEBUG_RODATA=y
            - CONFIG_DEBUG_SET_MODULE_RONX=y
            - CONFIG_DEFAULT_SECURITY_APPARMOR=y
            - CONFIG_DEVTMPFS_MOUNT=y
            - CONFIG_ENCRYPTED_KEYS=y
            - CONFIG_KEYS=y
            - CONFIG_NLS_CODEPAGE_437=y
            - CONFIG_NLS_ISO8859_1=y
            - CONFIG_RD_LZMA=y
            - CONFIG_SECCOMP_FILTER=y
            - CONFIG_SECURITY=y
            - CONFIG_SECURITY_APPARMOR=y
            - CONFIG_SQUASHFS=y
            - CONFIG_SQUASHFS_XATTR=y
            - CONFIG_SQUASHFS_XZ=y
            - CONFIG_STRICT_DEVMEM=y
            - CONFIG_SYN_COOKIES=y
            - CONFIG_SYSVIPC=y
            - CONFIG_SYSVIPC_SYSCTL=y
            - CONFIG_VFAT_FS=y
            - CONFIG_UFS_FS_WRITE=y
            - CONFIG_ISCSI_TCP=m
            - CONFIG_INFINIBAND_ISERT=m
            - CONFIG_NETFILTER_XT_MATCH_COMMENT=y
            - CONFIG_PCI_MSI=n
            - CONFIG_ATH10K=y
            - CONFIG_ATH10K_PCI=m
            - CONFIG_CRYPTO_CMAC=y
            - CONFIG_CFG80211=y
            - CONFIG_CFG80211_WEXT=y
            - CONFIG_MAC80211=y
            - CONFIG_MAC80211_DEBUGFS=y
            - CONFIG_BT_HCIUART_QCA=y
            - CONFIG_MEDIA_SUPPORT=y
            - CONFIG_DM_CRYPT=y
            - CONFIG_PINCTRL_SDM845=y
            - CONFIG_INTERCONNECT_QCOM_SDM845=y
            - CONFIG_ARM_GIC_PM=y
            - CONFIG_GPIO_UNIPHIER=y
            - CONFIG_GPIO_WCD934X=y
            - CONFIG_HAVE_SCHED_AVG_IRQ=y
            - CONFIG_HIBERNATE_CALLBACKS=y
            - CONFIG_PHY_UNIPHIER_USB2=y
            - CONFIG_PHY_UNIPHIER_USB3=y
            - CONFIG_IKCONFIG_PROC=y
            - CONFIG_IP_PNP_BOOTP=y
            - CONFIG_IP_PNP_DHCP=y
            - CONFIG_QCOM_RPMPD=y
            - CONFIG_SERIAL_QCOM_GENI_CONSOLE=y
            - CONFIG_ARCH_ALPINE=y
            - CONFIG_ARCH_ZX=y
            - CONFIG_ARM_SMMU_DISABLE_BYPASS_BY_DEFAULT=y
            - CONFIG_DRM_LEGACY=y
            - CONFIG_EFI_ARMSTUB_DTB_LOADER=y
            - CONFIG_ENABLE_MUST_CHECK=y
            - CONFIG_FW_LOADER_USER_HELPER_FALLBACK=y
            - CONFIG_IEEE802154_NL802154_EXPERIMENTAL=y
            - CONFIG_IKCONFIG=y
            - CONFIG_IP_PNP=y
            - CONFIG_IRQ_TIME_ACCOUNTING=y
            - CONFIG_LOGO=y
            - CONFIG_MEMCG_SWAP_ENABLED=y
            - CONFIG_MFD_WCD934X=y
            - CONFIG_NF_CONNTRACK_PROCFS=y
            - CONFIG_PNP_DEBUG_MESSAGES=y
            - CONFIG_POWER_RESET_BRCMSTB=y
            - CONFIG_POWER_RESET_XGENE=y
            - CONFIG_SCSI_UFSHCD=y
            - CONFIG_SCSI_UFSHCD_PCI=m
            - CONFIG_SCSI_UFS_DWC_TC_PCI=m
            - CONFIG_SCSI_UFSHCD_PLATFORM=y
            - CONFIG_SCSI_UFS_DWC_TC_PLATFORM=m
            - CONFIG_SCSI_UFS_QCOM=y
        override-pull: |
            snapcraftctl pull
        override-build: |
            cp debian/scripts/retpoline-extract-one \
                ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
            snapcraftctl build
            cp ${SNAPCRAFT_PART_INSTALL}/dtbs/qcom/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
            kernel_version=$(make kernelversion)
            commit=$(git log --pretty=format:'%h' -n 1)
            snapcraftctl set-version ${kernel_version}-focal-g${commit}
        organize:
            initrd.img: initrd
        prime:
            - -initrd*
            - -Image*
            - -kernel.img

    initrd-overlay:
        plugin: nil
        source: initrd-overlay
        after:
            - kernel
        override-build: |
            echo "Preparing overlay initrd"
            find . | cpio --quiet -o -H newc | lzma -7 > $SNAPCRAFT_PART_INSTALL/initrd-overlay.img
            cat $SNAPCRAFT_STAGE/initrd $SNAPCRAFT_PART_INSTALL/initrd-overlay.img > $SNAPCRAFT_PART_INSTALL/initrd.img
        prime:
            - initrd.img

    bootimg-db845:
        plugin: nil
        source: ubuntu
        after:
            - kernel
            - initrd-overlay
        override-build: |
            cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/sdm845-db845c.dtb > Image.gz+dtb845
            mkbootimg \
                --kernel Image.gz+dtb845 \
                --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
                --output ${SNAPCRAFT_PART_INSTALL}/boot.img \
                --pagesize 4096 \
                --base 0x80000000 \
                --kernel_offset 0x8000 \
                --ramdisk_offset 0x1000000 \
                --tags_offset 0x100 \
                --cmdline 'console=tty0 console=ttyMSM0,115200n8 root=/dev/disk/by-partlabel/writable net.ifnames=0 init=/lib/systemd/systemd ro rng_core.default_quality=700 panic=-1 fixrtc clk_ignore_unused pd_ignore_unused'
        prime:
            - boot.img

    skales:
        plugin: dump
        source: git://codeaurora.org/quic/kernel/skales
        prime:
            - -*

    bootimg:
        plugin: nil
        source: ubuntu
        after:
            - kernel
            - skales
            - initrd-overlay
        override-build: |
            python3 ${SNAPCRAFT_STAGE}/dtbTool -o dt.img -s 2048 ${SNAPCRAFT_STAGE}/dtbs/qcom/
            python3 ${SNAPCRAFT_STAGE}/mkbootimg \
                --kernel=${SNAPCRAFT_STAGE}/kernel.img \
                --dt=dt.img \
                --pagesize 2048 \
                --base 0x80000000 \
                --ramdisk=${SNAPCRAFT_STAGE}/initrd.img \
                --cmdline="console=ttyMSM0,115200n8 console=tty0 root=/dev/disk/by-label/writable net.ifnames=0 init=/lib/systemd/systemd ro rng_core.default_quality=700 panic=-1 fixrtc" \
                --output=${SNAPCRAFT_PART_INSTALL}/boot-db410c.img

            rm dt.img
            python3 ${SNAPCRAFT_STAGE}/dtbTool -o dt.img -s 4096 ${SNAPCRAFT_STAGE}/dtbs/qcom/
            python3 ${SNAPCRAFT_STAGE}/mkbootimg \
                --kernel=${SNAPCRAFT_STAGE}/kernel.img \
                --dt=dt.img \
                --pagesize 4096 \
                --base 0x80000000 \
                --ramdisk=${SNAPCRAFT_STAGE}/initrd.img \
                --cmdline="console=ttyMSM0,115200n8 console=tty0 root=/dev/disk/by-label/writable net.ifnames=0 init=/lib/systemd/systemd ro rng_core.default_quality=700 panic=-1 fixrtc" \
                --output=${SNAPCRAFT_PART_INSTALL}/boot-db820c.img
        prime:
            - boot-db410c.img
            - boot-db820c.img

    firmware:
        plugin: nil
        source: ubuntu
        stage-packages:
            - linux-firmware
            - linux-firmware-snapdragon:arm64
        override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx ${SNAPCRAFT_PART_INSTALL}/lib
            ln -s ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
            ln -sf /run/macaddr0             ${SNAPCRAFT_PART_INSTALL}/firmware/wlan/
            ln -sf /run/macaddr-wcn36xx      ${SNAPCRAFT_PART_INSTALL}/firmware/wlan/macaddr0
            ln -sf /run/macaddr-smsc75xx-1.3 ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx/ethmacaddr-1.3
            ln -sf /run/macaddr-smsc75xx-1.4 ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx/ethmacaddr-1.4
        stage:
            - -firmware/ath10k/QCA988X/hw2.0/firmware-5.bin
            - -firmware/ath10k/QCA4019/hw1.0/board-2.bin
            - -firmware/ath10k/QCA4019/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA6174/hw3.0/board-2.bin
            - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA9887/hw1.0/firmware-5.bin
            - -firmware/ath10k/QCA9888/hw2.0/board-2.bin
            - -firmware/ath10k/QCA9888/hw2.0/firmware-5.bin
            - -firmware/ath10k/QCA9984/hw1.0/board-2.bin
            - -firmware/ath10k/QCA9984/hw1.0/firmware-5.bin
            - -firmware/ath3k-1.fw
            - -firmware/wil6210.brd
            - -firmware/wil6210.fw
            - -firmware/a300_pfp.fw
            - -firmware/a300_pm4.fw
        organize:
            lib/firmware: firmware
        prime:
            - -usr
            - -lib

    firmware-ath10k:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-buster/buster/all/firmware-atheros_20190114-2+linaro2_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard410c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-buster/buster/all/firmware-qcom-dragonboard410c_1034.2.1-4_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware
        stage:
            - -boot

    firmware-dragonboard820c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-buster/buster/all/firmware-qcom-dragonboard820c_01700.1-3_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard845c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-buster/buster/all/firmware-qcom-dragonboard845c_20190529180356-v4+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-qcom-media:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-buster/buster/all/firmware-qcom-media_20190114-2+linaro2_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
