name: pi2-kernel
version: null
version-script: |
    . debian/debian.env
    dpkg-parsechangelog -l $DEBIAN/changelog -S version
summary: The Canonical raspi2 Linux kernel
description: The Canonical raspi2 Linux kernel
grade: stable
confinement: strict
type: kernel

parts:
  kernel:
    plugin: kernel
    source: .
    source-type: git
    kconfigflavour: raspi2
    kconfigs:
      - CONFIG_DEBUG_INFO=n
      - CONFIG_USB_LAN78XX=y
      - CONFIG_SERIAL_DEV_BUS=m
    kernel-image-target: zImage
    override-build: |
      snapcraftctl build
      tar -C $SNAPCRAFT_PART_INSTALL/dtbs -f $SNAPCRAFT_PART_INSTALL/dtbs/overlays.tgz -czv overlays
      rm -rf $SNAPCRAFT_PART_INSTALL/dtbs/overlays

  firmware:
    plugin: nil
    source: firmware
    after:
      - kernel
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    stage:
      - -usr
      - -lib
      - -firmware/brcm/brcmfmac43430-sdio.bin

  raspiwififw:
    plugin: nil
    source: firmware
    after:
      - firmware
    override-pull: |
      PKGS="http://ppa.launchpad.net/snappy-dev/image/ubuntu/dists/xenial/main/binary-armhf/Packages.gz"
      PKGPATH="$(wget -q -O- $PKGS|zcat|grep-dctrl raspberrypi-wireless-firmware |\
        grep Filename|tail -1| sed 's/^Filename: //')"
      wget http://ppa.launchpad.net/snappy-dev/image/ubuntu/$PKGPATH
      dpkg -x $(basename $PKGPATH) unpack/
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/firmware/brcm
      mv unpack/usr/share/doc/raspberrypi-wireless-firmware $SNAPCRAFT_PART_INSTALL/firmware/rpi-wlanfw-licenses
      mv unpack/lib/firmware/brcm80211/brcm/* $SNAPCRAFT_PART_INSTALL/firmware/brcm
    build-packages:
      - coreutils
      - dctrl-tools
      - sed
      - wget
      - libssl-dev
      - dpkg-dev
