name: xilinx-kernel
summary: Xilinx kernel for snappy
description: This is a Xilinx snapped kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
  kernel:
    after:
      - firmware
    plugin: kernel
    source: .
    source-type: git
    kdefconfig: [ "defconfig", "xilinx_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target: Image
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
      cp ${SNAPCRAFT_PART_INSTALL}/dtbs/xilinx/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
      ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
      snapcraftctl set-version $(git describe --tags | cut -c 15-)
    organize:
      initrd.img: initrd
    prime:
      - -initrd*

  initrd-overlay:
    plugin: nil
    source: initrd-overlay
    after:
      - kernel
      - firmware
    override-build: |
      echo "Preparing overlay initrd"
      mkdir -p lib/firmware
      cp -r ${SNAPCRAFT_STAGE}/firmware/regulatory.db* lib/firmware/
      find . | cpio --quiet -o -H newc | lzma -7 > $SNAPCRAFT_PART_INSTALL/initrd-overlay.img
      cat $SNAPCRAFT_STAGE/initrd $SNAPCRAFT_PART_INSTALL/initrd-overlay.img > $SNAPCRAFT_PART_INSTALL/initrd.img
    prime:
      - initrd.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    override-build: |
      snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx ${SNAPCRAFT_PART_INSTALL}/lib
      ln -s ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
    stage:
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/cavium
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/imx
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
    - dpkg-dev
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
