name: xilinx-kernel
summary: Xilinx kernel for snappy
description: This is a Xilinx snapped kernel
grade: stable
confinement: strict
type: kernel
adopt-info: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
  kernel:
    plugin: kernel
    source: .
    source-type: git
    kdefconfig: [ "defconfig", "xilinx_defconfig" ]
    kernel-with-firmware: false
    kernel-image-target: Image
    kconfigs:
      - CONFIG_DEBUG_INFO=n
    override-build: |
      cp debian/scripts/retpoline-extract-one \
        $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
      snapcraftctl build
      cp ${SNAPCRAFT_PART_INSTALL}/dtbs/xilinx/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
      ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
      snapcraftctl set-version $(git describe --tags | cut -c 15-)
  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib

build-packages:
    - dpkg-dev
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
