name: snapdragon-kernel
version: nil
version-script: |
    git describe --tags | cut -c 19-42
summary: Snapdragon kernel for snappy
description: This is a snapdragon snapped kernel, based off linaro kernel
grade: stable
confinement: strict
type: kernel

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

build-base: core18

parts:
    kernel:
        after:
            - firmware
            - firmware-atheros
            - firmware-dragonboard410c
            - firmware-dragonboard820c
            - firmware-dragonboard845c
            - firmware-qcom-media
            - firmware-qcom-soc
        plugin: kernel
        source: .
        source-type: git
        kconfigflavour: snapdragon
        kernel-with-firmware: false
        kernel-image-target: Image.gz
        kconfigs:
            - CONFIG_DEBUG_INFO=n
        override-build: |
            cp debian/scripts/retpoline-extract-one \
                ${SNAPCRAFT_PART_BUILD}/scripts/ubuntu-retpoline-extract-one
            snapcraftctl build
            cp ${SNAPCRAFT_PART_INSTALL}/dtbs/qcom/*.dtb ${SNAPCRAFT_PART_INSTALL}/dtbs/
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/lib
            ln -sf ../modules ${SNAPCRAFT_PART_INSTALL}/lib/modules
        kernel-initrd-core-base: core20
        kernel-initrd-flavour: edge
        kernel-initrd-modules:
            - aes
            - atl1c
            - atusb
            - camcc-sdm845
            - dm-crypt
            - drm
            - drm-kms-helper
            - gpio-wcd934x
            - ieee802154
            - ipa
            - ipvlan
            - libarc4
            - libcrc32c
            - lontium-lt9611
            - mac802154
            - mdt-loader
            - phy-qcom-qusb2
            - qcom-common
            - qcom-glink-smem
            - qmi-helpers
            - rtc-pm8xxx
            - sha256
            - slimbus
            - wcd934x
            - xhci-hcd
            - xhci-pci
            - xhci-plat-hcd
        kernel-initrd-firmware:
            - firmware/regulatory.db
            - firmware/regulatory.db.p7s
        stage:
            - System.map-*
            - config-*
            - dtbs
            - initrd.img
            - kernel.img
            - lib
            - modules
            - -modules/*/build
            - -modules/*/source
        prime:
            - -initrd.img
            - -kernel.img

    bootimg-db845:
        plugin: nil
        after:
            - kernel
        override-build: |
            cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/sdm845-db845c.dtb > Image.gz+dtb845
            mkbootimg \
                --kernel Image.gz+dtb845 \
                --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
                --output ${SNAPCRAFT_PART_INSTALL}/boot.img \
                --pagesize 4096 \
                --base 0x80000000 \
                --kernel_offset 0x8000 \
                --ramdisk_offset 0x1000000 \
                --tags_offset 0x100 \
                --cmdline 'console=tty0 console=ttyMSM0,115200n8 panic=-1 clk_ignore_unused pd_ignore_unused snapd_lk_boot_disk=sde'
        prime:
            - boot.img

    bootimg-db820:
        plugin: nil
        after:
            - kernel
        override-build: |
            cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8096-db820c.dtb > Image.gz+dtb820c
            mkbootimg \
                --kernel Image.gz+dtb820c \
                --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
                --output ${SNAPCRAFT_PART_INSTALL}/boot-db820c.img \
                --pagesize 4096 \
                --base 0x80000000 \
                --kernel_offset 0x8000 \
                --ramdisk_offset 0x1000000 \
                --tags_offset 0x100 \
                --cmdline 'console=tty0 console=ttyMSM0,115200n8 snapd_lk_boot_disk=sde'
            ln ${SNAPCRAFT_PART_INSTALL}/boot-db820c.img ${SNAPCRAFT_PART_INSTALL}/boot-ifc6640.img
        prime:
            - boot-db820c.img
            - boot-ifc6640.img

    bootimg-db410c:
        plugin: nil
        after:
            - kernel
        override-build: |
            cat ${SNAPCRAFT_STAGE}/kernel.img ${SNAPCRAFT_STAGE}/dtbs/qcom/apq8016-sbc.dtb > Image.gz+dtbdb410c
            mkbootimg \
                --kernel Image.gz+dtbdb410c \
                --ramdisk ${SNAPCRAFT_STAGE}/initrd.img \
                --output ${SNAPCRAFT_PART_INSTALL}/boot-db410c.img \
                --pagesize 2048 \
                --base 0x80000000 \
                --kernel_offset 0x8000 \
                --ramdisk_offset 0x1000000 \
                --tags_offset 0x100 \
                --cmdline 'console=tty0 console=ttyMSM0,115200n8 snapd_lk_boot_disk=mmcblk0'
        prime:
            - boot-db410c.img

    firmware:
        plugin: nil
        stage-packages:
            - wireless-regdb
        override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/firmware/wlan ${SNAPCRAFT_PART_INSTALL}/firmware/smsc75xx ${SNAPCRAFT_PART_INSTALL}/lib
            ln -s ../firmware ${SNAPCRAFT_PART_INSTALL}/lib/firmware
        organize:
            lib/firmware: firmware
        prime:
            - -usr
            - -lib

    firmware-atheros:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-atheros_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard410c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard410c_1034.2.1-5_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware
        stage:
            - -boot

    firmware-dragonboard820c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard820c_01700.1-4_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-dragonboard845c:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-dragonboard845c_20190529180356-v4+linaro6_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-qcom-media:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-media_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

    firmware-qcom-soc:
        plugin: dump
        source: http://obs.linaro.org/linaro-overlay-sid/sid/all/firmware-qcom-soc_20200817-1+linaro1_all.deb
        source-type: deb
        organize:
            lib/firmware: firmware

build-packages:
    - dpkg-dev
    - android-tools-mkbootimg
    - libssl-dev
    - libfdt-dev
    - cpio
    - flex
    - bison
